// Muscle paths for the LEFT side (x > 0), in rest-pose world coordinates.
// Each muscle is a list of "stations": origin, optional via points, insertion.
// A station is a polyline of [segment, [x, y, z]]; a muscle with several fibres
// spreads them across each station (fan-shaped muscles such as the pectoralis).
// Segments without a side (pelvis, lumbar, thorax, neck, head) are shared;
// sided segments (scapula, shoulder, elbow, wrist, hip, knee, ankle) get _L/_R.
// The right side is generated by mirroring x.

export const MUSCLE_GEOMETRY = [
  // ----- Trunk -----
  {
    id: 'rectus_abdominis', r: 0.011, fibers: 2, flat: 1.6,
    stations: [
      [['pelvis', [0.012, 0.905, 0.078]], ['pelvis', [0.035, 0.91, 0.078]]],
      [['lumbar', [0.02, 1.02, 0.11]], ['lumbar', [0.055, 1.02, 0.108]]],
      [['lumbar', [0.02, 1.13, 0.112]], ['lumbar', [0.06, 1.13, 0.108]]],
      [['thorax', [0.02, 1.235, 0.112]], ['thorax', [0.075, 1.23, 0.105]]],
    ],
  },
  {
    id: 'external_oblique', r: 0.011, fibers: 3, flat: 1.5,
    stations: [
      [['thorax', [0.12, 1.3, 0.075]], ['thorax', [0.14, 1.22, 0.04]], ['thorax', [0.135, 1.18, -0.02]]],
      [['lumbar', [0.1, 1.15, 0.085]], ['lumbar', [0.13, 1.1, 0.05]], ['lumbar', [0.135, 1.08, 0.0]]],
      [['pelvis', [0.05, 1.0, 0.095]], ['pelvis', [0.1, 0.99, 0.08]], ['pelvis', [0.14, 1.05, 0.0]]],
    ],
  },
  {
    id: 'erector_spinae', r: 0.014, fibers: 2,
    stations: [
      [['pelvis', [0.018, 0.99, -0.1]], ['pelvis', [0.045, 1.0, -0.095]]],
      [['lumbar', [0.022, 1.1, -0.1]], ['lumbar', [0.052, 1.1, -0.1]]],
      [['thorax', [0.022, 1.27, -0.105]], ['thorax', [0.062, 1.27, -0.11]]],
      [['thorax', [0.018, 1.4, -0.1]], ['thorax', [0.05, 1.4, -0.105]]],
      [['neck', [0.015, 1.53, -0.075]], ['thorax', [0.045, 1.45, -0.1]]],
    ],
  },
  {
    id: 'quadratus_lumborum', r: 0.012, fibers: 1,
    stations: [
      [['pelvis', [0.1, 1.045, -0.05]]],
      [['lumbar', [0.07, 1.12, -0.055]]],
      [['thorax', [0.055, 1.215, -0.06]]],
    ],
  },
  {
    id: 'iliopsoas', r: 0.016, fibers: 2,
    stations: [
      [['lumbar', [0.03, 1.13, -0.03]], ['pelvis', [0.11, 1.03, 0.0]]],
      [['pelvis', [0.045, 1.02, 0.0]], ['pelvis', [0.1, 0.99, 0.03]]],
      [['pelvis', [0.075, 0.955, 0.062]], ['pelvis', [0.085, 0.955, 0.062]]],
      [['hip', [0.078, 0.855, 0.015]], ['hip', [0.082, 0.855, 0.015]]],
    ],
  },
  {
    id: 'latissimus_dorsi', r: 0.011, fibers: 5, flat: 1.4,
    stations: [
      [['thorax', [0.01, 1.34, -0.12]], ['thorax', [0.015, 1.22, -0.105]], ['lumbar', [0.02, 1.1, -0.1]], ['pelvis', [0.1, 1.05, -0.07]]],
      [['thorax', [0.1, 1.32, -0.115]], ['thorax', [0.12, 1.26, -0.1]], ['thorax', [0.14, 1.22, -0.06]]],
      [['thorax', [0.15, 1.32, -0.055]]],
      [['shoulder', [0.185, 1.33, 0.012]]],
    ],
  },
  {
    id: 'trapezius', r: 0.01, fibers: 6, flat: 1.5,
    stations: [
      [['head', [0.0, 1.625, -0.085]], ['neck', [0.0, 1.53, -0.085]], ['thorax', [0.0, 1.46, -0.1]], ['thorax', [0.0, 1.36, -0.12]], ['thorax', [0.0, 1.23, -0.105]]],
      [['scapula', [0.12, 1.455, 0.025]], ['scapula', [0.17, 1.465, -0.025]], ['scapula', [0.14, 1.435, -0.09]], ['scapula', [0.085, 1.41, -0.11]]],
    ],
  },
  {
    id: 'pectoralis_major', r: 0.011, fibers: 6, flat: 1.5,
    stations: [
      [['scapula', [0.1, 1.445, 0.075]], ['scapula', [0.04, 1.44, 0.092]], ['thorax', [0.012, 1.4, 0.115]], ['thorax', [0.012, 1.3, 0.125]], ['thorax', [0.05, 1.245, 0.118]]],
      [['thorax', [0.1, 1.37, 0.1]], ['thorax', [0.1, 1.3, 0.1]]],
      [['shoulder', [0.19, 1.335, 0.03]]],
    ],
  },
  {
    id: 'pectoralis_minor', r: 0.008, fibers: 2,
    stations: [
      [['thorax', [0.07, 1.34, 0.108]], ['thorax', [0.09, 1.28, 0.1]]],
      [['scapula', [0.145, 1.41, 0.038]]],
    ],
  },
  {
    id: 'serratus_anterior', r: 0.008, fibers: 4,
    stations: [
      [['thorax', [0.125, 1.35, 0.06]], ['thorax', [0.14, 1.29, 0.05]], ['thorax', [0.14, 1.24, 0.03]], ['thorax', [0.13, 1.2, 0.01]]],
      [['thorax', [0.145, 1.36, -0.02]], ['thorax', [0.15, 1.3, -0.04]], ['thorax', [0.145, 1.24, -0.05]]],
      [['scapula', [0.08, 1.43, -0.09]], ['scapula', [0.085, 1.29, -0.095]]],
    ],
  },
  {
    id: 'rhomboids', r: 0.008, fibers: 3, flat: 1.4,
    stations: [
      [['neck', [0.0, 1.5, -0.08]], ['thorax', [0.0, 1.35, -0.11]]],
      [['scapula', [0.077, 1.425, -0.1]], ['scapula', [0.087, 1.3, -0.1]]],
    ],
  },
  {
    id: 'levator_scapulae', r: 0.008, fibers: 1,
    stations: [
      [['neck', [0.03, 1.56, -0.045]]],
      [['neck', [0.05, 1.5, -0.065]]],
      [['scapula', [0.085, 1.44, -0.095]]],
    ],
  },
  {
    id: 'sternocleidomastoid', r: 0.009, fibers: 1,
    stations: [
      [['head', [0.052, 1.605, -0.025]]],
      [['neck', [0.04, 1.52, 0.03]]],
      [['thorax', [0.018, 1.43, 0.095]]],
    ],
  },
  // ----- Shoulder & arm -----
  {
    id: 'deltoid', r: 0.017, fibers: 3,
    stations: [
      [['scapula', [0.14, 1.455, 0.045]], ['scapula', [0.18, 1.465, -0.01]], ['scapula', [0.15, 1.44, -0.08]]],
      [['shoulder', [0.2, 1.42, 0.05]], ['shoulder', [0.235, 1.415, -0.01]], ['shoulder', [0.2, 1.415, -0.07]]],
      [['shoulder', [0.225, 1.33, 0.02]], ['shoulder', [0.235, 1.33, -0.015]], ['shoulder', [0.222, 1.33, -0.045]]],
      [['shoulder', [0.215, 1.27, -0.005]]],
    ],
  },
  {
    id: 'supraspinatus', r: 0.009, fibers: 1,
    stations: [
      [['scapula', [0.1, 1.43, -0.1]]],
      [['scapula', [0.16, 1.45, -0.05]]],
      [['shoulder', [0.212, 1.425, -0.005]]],
    ],
  },
  {
    id: 'infraspinatus', r: 0.012, fibers: 2,
    stations: [
      [['scapula', [0.09, 1.36, -0.105]], ['scapula', [0.1, 1.31, -0.1]]],
      [['scapula', [0.16, 1.38, -0.075]]],
      [['shoulder', [0.215, 1.395, -0.04]]],
    ],
  },
  {
    id: 'biceps_brachii', r: 0.017, fibers: 2,
    stations: [
      [['scapula', [0.172, 1.425, -0.01]], ['scapula', [0.15, 1.41, 0.035]]],
      [['shoulder', [0.205, 1.35, 0.035]], ['shoulder', [0.19, 1.35, 0.04]]],
      [['shoulder', [0.205, 1.2, 0.042]]],
      [['elbow', [0.205, 1.06, 0.02]]],
    ],
  },
  {
    id: 'triceps_brachii', r: 0.018, fibers: 2,
    stations: [
      [['scapula', [0.175, 1.37, -0.045]], ['shoulder', [0.225, 1.33, -0.03]]],
      [['shoulder', [0.195, 1.22, -0.05]], ['shoulder', [0.215, 1.22, -0.05]]],
      [['shoulder', [0.203, 1.13, -0.045]]],
      [['elbow', [0.19, 1.09, -0.05]]],
    ],
  },
  {
    id: 'forearm_flexors', r: 0.012, fibers: 2,
    stations: [
      [['shoulder', [0.175, 1.105, -0.02]]],
      [['elbow', [0.195, 1.02, 0.018]], ['elbow', [0.215, 1.02, 0.02]]],
      [['wrist', [0.2, 0.845, 0.014]], ['wrist', [0.22, 0.845, 0.014]]],
    ],
  },
  {
    id: 'forearm_extensors', r: 0.011, fibers: 2,
    stations: [
      [['shoulder', [0.232, 1.105, -0.02]]],
      [['elbow', [0.235, 1.02, -0.015]], ['elbow', [0.21, 1.02, -0.03]]],
      [['wrist', [0.225, 0.845, -0.012]], ['wrist', [0.2, 0.845, -0.012]]],
    ],
  },
  // ----- Hip & thigh -----
  {
    id: 'gluteus_maximus', r: 0.026, fibers: 4,
    stations: [
      [['pelvis', [0.07, 1.05, -0.085]], ['pelvis', [0.04, 0.99, -0.1]], ['pelvis', [0.02, 0.93, -0.1]], ['pelvis', [0.02, 0.89, -0.085]]],
      [['pelvis', [0.11, 1.0, -0.12]], ['pelvis', [0.09, 0.9, -0.12]]],
      [['hip', [0.165, 0.87, -0.04]], ['hip', [0.15, 0.8, -0.035]]],
    ],
  },
  {
    id: 'gluteus_medius', r: 0.02, fibers: 3,
    stations: [
      [['pelvis', [0.09, 1.055, -0.07]], ['pelvis', [0.14, 1.07, -0.01]], ['pelvis', [0.13, 1.04, 0.05]]],
      [['pelvis', [0.15, 1.0, -0.035]], ['pelvis', [0.165, 1.0, 0.0]], ['pelvis', [0.155, 0.99, 0.025]]],
      [['hip', [0.165, 0.935, -0.012]]],
    ],
  },
  {
    id: 'piriformis', r: 0.01, fibers: 1,
    stations: [
      [['pelvis', [0.025, 0.97, -0.085]]],
      [['pelvis', [0.09, 0.95, -0.08]]],
      [['hip', [0.155, 0.94, -0.025]]],
    ],
  },
  {
    id: 'tfl_itb', r: 0.009, fibers: 1,
    stations: [
      [['pelvis', [0.135, 1.03, 0.05]]],
      [['hip', [0.165, 0.88, 0.02]]],
      [['hip', [0.16, 0.7, 0.0]]],
      [['hip', [0.14, 0.53, -0.005]]],
      [['knee', [0.13, 0.46, 0.02]]],
    ],
  },
  {
    id: 'rectus_femoris', r: 0.02, fibers: 1,
    stations: [
      [['pelvis', [0.105, 0.99, 0.07]]],
      [['hip', [0.105, 0.88, 0.075]]],
      [['hip', [0.105, 0.72, 0.085]]],
      [['hip', [0.098, 0.56, 0.065]]],
      [['knee', [0.087, 0.45, 0.045]]],
    ],
  },
  {
    id: 'vastus_lateralis', r: 0.024, fibers: 1,
    stations: [
      [['hip', [0.16, 0.88, 0.0]]],
      [['hip', [0.155, 0.7, 0.03]]],
      [['hip', [0.12, 0.56, 0.06]]],
      [['knee', [0.095, 0.47, 0.05]]],
    ],
  },
  {
    id: 'vastus_medialis', r: 0.023, fibers: 1,
    stations: [
      [['hip', [0.075, 0.82, 0.03]]],
      [['hip', [0.058, 0.62, 0.035]]],
      [['hip', [0.075, 0.55, 0.06]]],
      [['knee', [0.09, 0.47, 0.05]]],
    ],
  },
  {
    id: 'hamstrings', r: 0.02, fibers: 2,
    stations: [
      [['pelvis', [0.058, 0.87, -0.055]], ['pelvis', [0.068, 0.87, -0.055]]],
      [['hip', [0.07, 0.75, -0.07]], ['hip', [0.125, 0.75, -0.07]]],
      [['hip', [0.068, 0.57, -0.055]], ['hip', [0.135, 0.57, -0.05]]],
      [['knee', [0.07, 0.45, -0.005]], ['knee', [0.135, 0.46, -0.015]]],
    ],
  },
  {
    id: 'adductors', r: 0.02, fibers: 3,
    stations: [
      [['pelvis', [0.02, 0.9, 0.07]], ['pelvis', [0.035, 0.875, 0.03]], ['pelvis', [0.055, 0.865, -0.035]]],
      [['hip', [0.06, 0.8, 0.01]], ['hip', [0.055, 0.72, 0.0]], ['hip', [0.06, 0.64, -0.025]]],
      [['hip', [0.105, 0.78, -0.02]], ['hip', [0.1, 0.66, -0.02]], ['hip', [0.075, 0.54, -0.02]]],
    ],
  },
  {
    id: 'sartorius', r: 0.009, fibers: 1,
    stations: [
      [['pelvis', [0.125, 1.015, 0.07]]],
      [['hip', [0.1, 0.84, 0.075]]],
      [['hip', [0.055, 0.68, 0.045]]],
      [['hip', [0.05, 0.54, -0.01]]],
      [['knee', [0.075, 0.44, 0.025]]],
    ],
  },
  // ----- Lower leg -----
  {
    id: 'gastrocnemius', r: 0.022, fibers: 2,
    stations: [
      [['hip', [0.075, 0.54, -0.03]], ['hip', [0.118, 0.54, -0.03]]],
      [['knee', [0.075, 0.38, -0.06]], ['knee', [0.12, 0.38, -0.055]]],
      [['knee', [0.088, 0.2, -0.045]]],
      [['ankle', [0.09, 0.05, -0.078]]],
    ],
  },
  {
    id: 'soleus', r: 0.02, fibers: 1,
    stations: [
      [['knee', [0.11, 0.44, -0.035]]],
      [['knee', [0.1, 0.28, -0.05]]],
      [['knee', [0.09, 0.15, -0.04]]],
      [['ankle', [0.09, 0.05, -0.075]]],
    ],
  },
  {
    id: 'tibialis_anterior', r: 0.013, fibers: 1,
    stations: [
      [['knee', [0.12, 0.44, 0.03]]],
      [['knee', [0.113, 0.28, 0.035]]],
      [['knee', [0.095, 0.12, 0.035]]],
      [['ankle', [0.075, 0.06, 0.05]]],
    ],
  },
];
